---
title: "Power BI"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Introduction
本リポジトリは [Power BI Desktop](https://powerbi.microsoft.com/ja-jp/desktop/){target="_blank" title="Microsoft"} においてRのスクリプトを実行するための情報を整理しているリポジトリです。  
　  

## Aboout Power BI Desktop
Power BI DesktopはマイクロソフトのBI（Business Intelligence）製品です。その特徴は  
　  

> Power BIは、データを視覚化して、組織全体で洞察を共有し、アプリやWebサイトにその洞察を埋め込むことができるビジネス分析ソリューションです。数百ものデータソースに接続し、ライブダッシュボードおよびレポートでデータを活用します。 [出典](https://powerbi.microsoft.com/ja-jp/what-is-power-bi/){target="_blank" title="Microsoft Power BI"} 

　  
Power BIは複数のリリース形態がありますが [Desktop版](https://powerbi.microsoft.com/ja-jp/desktop/){target="_blank" title="Microsoft Power BI"} であればフリーで使えインタラクティブな環境でデータの分析と可視化ができます。また、RやPythonとの連携が可能で、外部IDEとしてRStudio Desktopの利用が可能なため使い慣れた開発環境で連携のためのスクリプトを記述することができます。  
[Kibana](https://www.elastic.co/jp/products/kibana){target="_blank" title=""} は敷居が高いというような方に向いています。  
　  


# License
[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ja){target="_blank" title="ライセンスの要約"} , Sampo Suzuki

* 表示
    * あなたは 適切なクレジットを表示し、ライセンスへのリンクを提供し、変更があったらその旨を示さなければなりません。これらは合理的であればどのような方法で行っても構いませんが、許諾者があなたやあなたの利用行為を支持していると示唆するような方法は除きます。
* 非営利
    * あなたは営利目的でこの資料を利用してはなりません。
* 継承
    * もしあなたがこの資料をリミックスしたり、改変したり、加工した場合には、あなたはあなたの貢献部分を元の作品と同じライセンスの下に頒布しなければなりません。
